config/routes.rb
Rails.application.routes.draw do

  root to: 'static#home'

  get 'auth/twitter' => 'auth/twitter#auth', as: :twitter_auth
  get 'auth/twitter/callback' => 'auth/twitter#callback', as: :twitter_callback

  get 'auth/:site', to: 'auth/oauth#auth', as: :oauth_authorisation, constraints: { site: /google|linkedin|facebook/ }
  get 'auth/:site/callback', to: 'auth/oauth#callback', as: :oauth_callback, constraints: { site: /google|linkedin|facebook/ }


  resources :links

  namespace :api do
    resources :links, only: [:index, :destroy]
  end

  require 'sidekiq/web'
  require 'sidetiq/web'
  mount Sidekiq::Web => '/sidekiq'

  class Oauth2Constraint

    def self.matches?(request)

    end

  end
end

app/models/link.rb
require 'open-uri'

class Link < ActiveRecord::Base
	belongs_to :user
	has_many :link_posts

	before_validation :populate_metadata

	validates :url, uniqueness: true, presence: true
	validates :title, presence: true

	def self.normalised_url(url)
		resolved_uri = MetaInspector.new(url).url
		uri = Addressable::URI.parse(resolved_uri)
		uri.scheme = "http"
		uri.normalize
		uri.fragment = nil
		# Strip UTM query params
		if uri.query
			query_hash = uri.query_values
			query_hash.reject! { |k,_| k =~ /utm/ }
			uri.query_values = query_hash
		end
		uri.to_s.gsub(/\?\z/, "")
	end

	def populate_metadata
		page = MetaInspector.new(url)
		errors.add(:url) unless page.response.status < 400
		errors.add(:content_type) unless page.content_type == "text/html"
		if page.title.blank?
			self.title = self.title || page.host
		else
			self.title = page.title
		end
		self.description = self.description || page.description 
		self.image_url = self.image_url || page.images.best
	end

	def host
		Addressable::URI.parse(url).host
	end

end

app/controllers/api/links_controller.rb
class Api::LinksController < ApplicationController

	def index
		params[:filter] = "network" unless ["network", "self", "recommended"].include? params[:filter]
		if params[:filter] == "network"
			@link_posts = current_user.link_posts.network.order("posted_at DESC").limit(20).includes(:link)
		elsif params[:filter] == "self"
			@link_posts = current_user.link_posts.owned.order("posted_at DESC").limit(20).includes(:link)
		elsif params[:filter] == "recommended"
		end
	end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def index
		params[:filter] = "network" unless ["network", "self", "recommended"].include? params[:filter]
		if params[:filter] == "network"
			@link_posts = current_user.link_posts.network.order("posted_at DESC").limit(20).includes(:link)
		elsif params[:filter] == "self"
			@link_posts = current_user.link_posts.owned.order("posted_at DESC").limit(20).includes(:link)
		elsif params[:filter] == "recommended"
		end
	end

	def show
	end

end

app/helpers/links_helper.rb
module LinksHelper
	
	def date_change?(posts, current_index)
		if current_index == 0 || posts[current_index].posted_at.day != posts[current_index-1].posted_at.day
			true
		end
	end

end

app/views/links/index.html.slim
#sidebar-wrapper

	.sidebar-nav
    .social-connect
      a.btn.btn-facebook.btn-social.btn-block href="/auth/facebook"  
        i.fa.fa-facebook
        | Connect to Facebook
      a.btn.btn-twitter.btn-social.btn-block href="/auth/twitter"  
        i.fa.fa-twitter
        | Connect to Twitter
      a.btn.btn-linkedin.btn-social.btn-block href="/auth/linkedin"  
        i.fa.fa-linkedin
        | Connect to LinkedIn
      a.btn.btn-google-plus.btn-social.btn-block href="/auth/google"  
        i.fa.fa-google-plus
        | Connect to Google+

#page-content-wrapper
	.container-fluid
    .row
      .col-sm-12
      	a#menu-toggle href="#menu-toggle"
          i.fa.fa-bars

      .col-sm-12
      	ul.filter-menu
          li class="#{'active' if params[:filter] == 'network'}"
      			=link_to "Network", links_path(filter: "network")
          li class="#{'active' if params[:filter] == 'self'}"
      			=link_to "My Links", links_path(filter: "self")
        .clearfix


      	ul.links
          -@link_posts.each_with_index do |post, index|

            -if index == 0 || date_change?(@link_posts, index)
              li.date =post.posted_at.strftime("%d %^b %Y")
            li.link
              .row
                .link-image.col-sm-2
                  =link_to post.link.url, target: "_blank" do
                    =image_tag post.link.image_url
                .link-info.col-sm-10
                  =link_to post.link.url, target: "_blank" do
                    .title =post.link.title
                  .description =post.link.description
                  .url =post.link.host
                  .meta
                    .posted-by = "via #{post.posted_by}"

app/views/links/show.html.slim
h3 Remove frame

iframe src=params[:url] width="100%" height="100%" frameborder="0"